const RecommendationPanel = ({ recommendation }) => {
  if (!recommendation) {
    return (
      <div className="bg-white p-6 rounded-xl shadow">
        <p className="text-gray-500">
          Select a recommendation to view explanation
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white p-6 rounded-xl shadow">
      <h3 className="text-xl font-bold mb-2">{recommendation.title}</h3>

      <p className="text-gray-600">{recommendation.description}</p>

      <div className="mt-4">
        <h4 className="font-semibold mb-1">AI Reasoning</h4>
        <p className="text-gray-500 text-sm">
          This recommendation is generated by analyzing financial indicators
          including burn rate, profit margin, liquidity levels, and debt
          exposure.
        </p>
      </div>
    </div>
  );
};

export default RecommendationPanel;